- name: Add members to group
  hosts: localhost
  gather_facts: false
  vars_files:
    - "vars/team_members.yml"
  tasks:
    - name: add users to group
      uri:
        method: POST
        url: "https://api.opsgenie.com/v2/teams/{{ item.teamname }}/members?teamIdentifierType=name"
        headers:
          Content-Type: application/json
          Authorization: "GenieKey {{ api_key }}"
        body:
          user: "{{ item.user }}"
          role: "{{ item.role }}"
        body_format: json
        return_content: true
      with_items:
        - "{{ team_members }}"
      register: team_updated
