---
- name: Create OpsGenie Schedule Rotation
  hosts: localhost
  gather_facts: false
  vars_files: 
    - "vars/schedule_rotation.yml"
  tasks:
    - name: create schedule rotation
      uri:
        method: POST
        url: https://api.opsgenie.com/v2/schedules/{{ item.scheduleName }}/rotations?scheduleIdentifierType=name
        headers:
          Content-Type: application/json
          Authorization: "GenieKey {{ api_key }}"
        body:
          name: "{{ item.rt_name  | default(omit) }}"
          startDate: "{{ item.startDate  | default(omit) }}"
          endDate: "{{ item.endDate  | default(omit) }}"
          type: "{{ item.type  | default(omit) }}"
          length: "{{ item.length  | default(omit) }}"
          participants: "{{ item.participants | default(omit) }}"
        body_format: json
        status_code: 201
      with_items:
        - "{{ rotation }}"
      register: rotation_created
      changed_when: rotation_created.status == 201

    - name: "Ansible | Print rotation_created"
      debug:
        msg: "rotation_created: {{ rotation_created }}"