---
- name: Create OpsGenie Teams
  hosts: localhost
  gather_facts: false
  vars_files: 
    - "vars/teams.yml"
  tasks:
    - name: Get List of all Teams
      uri:
        method: GET
        url: "https://api.opsgenie.com/v2/teams"
        headers:
          Authorization: "GenieKey {{ api_key }}"
        return_content: yes
      register: team_id
      ignore_errors: true

    - name: Create a list of all existing team names and respected ID's
      set_fact:
        existing_team_id: "{{ team_id.json.data | map(attribute='id') | list }}"
        existing_team_name: "{{ team_id.json.data | map(attribute='name') | list }}"

    - name: "Ansible | Print existing_team_name"
      debug:
        msg: "existing_team_name: {{ existing_team_name }}"

    - name: create team if it doesnt exist
      uri:
        method: POST
        url: https://api.opsgenie.com/v2/teams
        headers:
          Content-Type: application/json
          Authorization: "GenieKey {{ api_key }}"
        body:
          name: "{{ item.name }}"
          description: "{{ item.description | default(omit) }}"
          members: "{{ item.members | default(omit) }}"
        body_format: json
        status_code: 201
      when: item.name not in existing_team_name
      with_items:
        - "{{ team }}"
      # loop: "{{ team|subelements('members') }}"
      # loop_control:
      #   label: "{{ item.0.name }}"
      register: team_created
      changed_when: team_created.status == 201

    - name: "Ansible | Print team_created"
      debug:
        msg: "user_created: {{ team_created }}"