---
- name: Create OpsGenie Schedule
  hosts: localhost
  gather_facts: false
  vars_files: 
    - "vars/schedule.yml"
  tasks:
    - name: create schedule
      uri:
        method: POST
        url: https://api.opsgenie.com/v2/schedules
        headers:
          Content-Type: application/json
          Authorization: "GenieKey {{ api_key }}"
        body:
          name: "{{ item.name }}"
          description: "{{ item.description | default(omit) }}"
          timezone: "{{ item.timezone | default(omit) }}"
          enabled: "{{ item.enabled | default(omit) }}"
          ownerTeam:
            name: "{{ item.ownerTeam | default(omit) }}"
        body_format: json
        status_code: 201
      with_items:
        - "{{ schedule }}"
      register: schedule_created
      changed_when: schedule_created.status == 201

    - name: "Ansible | Print schedule_created"
      debug:
        msg: "schedule_created: {{ schedule_created }}"