---
- name: Playbooks execution wrapper
  hosts: localhost
  gather_facts: false
  tasks:

    - name: User Management
      include_tasks: tasks/users.yml
      tags:
        - users
        - general

    - name: Team Management
      include_tasks: tasks/teams.yml
      tags:
        - teams
        - general

    - name: Manage Team Members
      include_tasks: tasks/add_members_to_team.yml
      tags:
        - members
        - general

    - name: Manage Schedules
      include_tasks: tasks/schedules.yml
      tags:
        - schedules
        - general

    - name: Manage Notifications
      include_tasks: tasks/create_notifications.yml
      tags:
        - notifications
        - general
