---
- name: Playbooks execution wrapper
  hosts: localhost
  gather_facts: false
  tasks:
    - name: User Management
      include_tasks: tasks/users.yml
      tags: users

    - name: Team Management
      include_tasks: tasks/teams.yml
      tags: teams

    - name: Manage Team Members
      include_tasks: tasks/team_members.yml
      tags: members

    - name: Manage Schedules
      include_tasks: tasks/schedules.yml
      tags: schedules

    - name: Manage Schedules Rotations
      include_tasks: tasks/schedule_rotations.yml
      tags: rotations

    - name: Manage Notifications
      include_tasks: tasks/notifications.yml
      tags: notifications