---
- name: Create OpsGenie Notification
  hosts: localhost
  gather_facts: false
  vars_files: 
    - "vars/opsgenie.yml"
  tasks:
    - name: create Notification
      uri:
        method: POST
        url: https://api.opsgenie.com/v2/users/{{ item.user }}/notification-rules
        headers:
          Content-Type: application/json
          Authorization: "GenieKey {{ api_key }}"
        body:
          name: "{{ item.name }}"
          actionType: "{{ item.actionType | default(omit) }}"
          enabled: "{{ item.enabled | default(omit) }}"
          criteria: "{{ item.criteria | default(omit) }}"
          order: "{{ item.order | default(omit) }}"
          notificationTime: "{{ item.notificationTime | default(omit) }}"
          #schedules: "{{ item.schedules | default(omit) }}"
          repeat: "{{ item.repeat | default(omit) }}"
          #timeRestriction: "{{ item.timeRestriction | default(omit) }}"
        body_format: json
        status_code: 201
      with_items:
        - "{{ notification }}"
      register: notificatione_created
      changed_when: notificatione_created.status == 201

    - name: "Ansible | Print notificatione_created"
      debug:
        msg: "notificatione_created: {{ notificatione_created }}"
