---
- name: Reading variables file
  include_vars:
    name: file_vars
    file: "vars/opsgenie_test.yml"
  tags: schedules

- name: Get list of all schedules
  uri:
    method: GET
    url: "https://api.opsgenie.com/v2/schedules"
    headers:
      Authorization: "GenieKey {{ api_key }}"
    return_content: yes
  register: existing_schedules
  ignore_errors: true
  tags: schedules

- name: "Schedule | Create a list of all names"
  set_fact:
    existing_schedule_names: "{{  existing_schedules.json.data | map(attribute='name') | list }}"
  tags: schedules

- name: "Schedule | List Schedules"
  debug:
    msg: "existing_schedule_names: {{ existing_schedule_names }}"
  tags: schedules

# Create Schedules
- name: "Schedule | Create Schedule"
  uri:
    method: POST
    url: https://api.opsgenie.com/v2/schedules
    headers:
      Content-Type: application/json
      Authorization: "GenieKey {{ api_key }}"
    body:
      name: "{{ item.schedule_name }}"
      description: "{{ item.description | default(omit) }}"
      timezone: "{{ item.timezone | default(omit) }}"
      enabled: "{{ item.enabled | default(omit) }}"
      ownerTeam:
        name: "{{ item.ownerTeam | default(omit) }}"
      rotation: "{{ item.rotation | default(omit) }}"
      timeRestriction: "{{ item.timeRestriction | default(omit) }}"
    body_format: json
    status_code: 201
  when: item.schedule_name not in existing_schedule_names
  with_items:
    - "{{ file_vars.schedules }}"
  register: schedule_created
  changed_when: schedule_created.status == 201
  tags: schedules

# Update Schedules
- name: "Schedule | Update Schedule"
  uri:
    method: PATCH
    url: https://api.opsgenie.com/v2/schedules/{{ item.schedule_name }}?identifierType=name
    headers:
      Content-Type: application/json
      Authorization: "GenieKey {{ api_key }}"
    body:
      name: "{{ item.schedule_name }}"
      description: "{{ item.description | default(omit) }}"
      timezone: "{{ item.timezone | default(omit) }}"
      enabled: "{{ item.enabled | default(omit) }}"
      ownerTeam:
        name: "{{ item.ownerTeam | default(omit) }}"
      rotation: "{{ item.rotation | default(omit) }}"
      timeRestriction: "{{ item.timeRestriction | default(omit) }}"
    body_format: json
    status_code: 200
  when: item.schedule_name in existing_schedule_names
  with_items:
    - "{{ file_vars.schedules }}"
  register: schedule_updated
  changed_when: schedule_updated.status == 200
  tags: schedules

# Schedule Rotations
# List rotations
- name: Get list of all rotations
  uri:
    method: GET
    url: "https://api.opsgenie.com/v2/schedules/{{ item }}/rotations?scheduleIdentifierType=name"
    headers:
      Authorization: "GenieKey {{ api_key }}"
    return_content: yes
  with_items:
    - "{{ existing_schedule_names }}"
  register: existing_rotations
  ignore_errors: true
  tags: schedules

# Update Rotations
- name: update schedule rotation
  uri:
    method: PATCH
    url: https://api.opsgenie.com/v2/schedules/{{ item.1.scheduleName }}/rotations/{{ item.0.json.data.0.id }}?scheduleIdentifierType=name
    headers:
      Content-Type: application/json
      Authorization: "GenieKey {{ api_key }}"
    body:
      name: "{{ item.1.name  | default(omit) }}"
      startDate: "{{ item.1.startDate  | default(omit) }}"
      endDate: "{{ item.1.endDate  | default(omit) }}"
      type: "{{ item.1.type  | default(omit) }}"
      length: "{{ item.1.length  | default(omit) }}"
      participants: "{{ item.1.participants | default(omit) }}"
    body_format: json
    status_code: 200
  when: item.0.item == item[1]['scheduleName']
  with_nested:
    - "{{ existing_rotations.results }}"
    - "{{ file_vars.rotations }}"
  ignore_errors: true
  tags: schedules